name: cryptography inventory
on:
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
jobs:
  qtrace:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: TGT-Quant0/qtrace-action@v1
        with:
          path: .
